name: shop_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  get: ^4.6.5
  flutter_iconly: ^1.0.2
  dots_indicator: ^2.1.0
  badges: ^2.0.3
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.6
  flutter_facebook_auth: ^5.0.6
  fluttertoast: ^8.1.1
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  firebase_storage: ^11.0.2
  google_sign_in: ^5.4.2
  firebase_messaging: ^14.1.1
  overlay_support: ^2.1.0
  cached_network_image: ^3.2.2
  google_nav_bar: ^5.0.6
  get_storage: ^2.0.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/offers/
    - assets/images/shoes/
    - assets/images/tshirts/
    - assets/images/suts/
    - assets/images/shirts/
    - assets/images/pants/
    - assets/images/dresses/
    - assets/images/clips/
